# This is to set the order of vars in csvs

order_header_premerge_csv <- c(
     "id",
     "data_source",
     "country",
     "hemisphere",
     "week",
     "year",
     "age_group",
     "hsp_rate",
     "hsp_rate_flu",
     "hsp_rate_rsv",
     "hsp_rate_covid19",
     "cases_rate_flu",
     "cases_rate_rsv",
     "cases_rate_covid19",
     "hsp_abs",
     "hsp_abs_flu",
     "hsp_abs_rsv",
     "hsp_abs_covid",
     "cases_abs_flu",
     "cases_abs_rsv",
     "cases_abs_covid" ,
     "denominator",
     "subtype_a_abs",
     "subtype_b_abs",
     "subtype_c_abs",
     "subtype_a_rate",
     "subtype_b_rate",
     "subtype_c_rate"
)
